name: Changeset Check

on:
  pull_request:
    branches:
      - main

jobs:
  changeset:
    name: Check for changeset file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node, pnpm and dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Check for changeset
        run: pnpm changeset status --since origin/main
