name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

env:
  # Opt in now to the runtime that will become default on GitHub-hosted runners.
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node, pnpm and dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Echo secret from actions secrets
        uses: ./.github/actions/echo-secret
        with:
          secret-name: MY_SECRET
          var-name: MY_VAR
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_VAR: ${{ vars.MY_VAR }}

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
